# my twine key is in
#         TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

name: Publish brightest-path-lib (cudmore)

on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]
    #branches: [main]

jobs:

  publish-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        pip install setuptools wheel numpy transonic psutil twine build
    - name: Publish tp PyPi with twine (macOS)
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
        # TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        git tag
        python -m build .
        twine upload dist/* --verbose
    #   continue-on-error: true